### PR TITLE
Update docker source to aliyun.

### PR DESCRIPTION
**Pull request by zycv**

### CODE REVIEW

**Comment by SunAriesCN** [comment]
I think it seems not suitable for developers on other countries.

**Comment by SunAriesCN** [comment]
@Duan-JM Hi Demo, can we have a new dockerfile and add some guides on README.md to solve this PR problem?

**Comment by SunAriesCN** [comment]
> @Duan-JM Hi Demo, can we have a new dockerfile and add some guides on README.md to solve this PR problem?

Here is the [reference](https://github.com/tensorflow/models/tree/master/research/object_detection/dockerfiles).

**Comment by Duan-JM** [comment]
@SunAriesCN Hi, SunAriesCN, the reason is vague for me to create a new dockerfile. As far as I concerned, once we create a new dockerfile as [this reference](https://github.com/tensorflow/models/tree/master/research/object_detection/dockerfiles), it means that we classify docker according to countries. Feel free to correct me at this point~

**Comment by zycv** [comment]
It seems that create multiple dockers for different countries may not be appropriate, I will close this PR until we have a better solution.
But when building for the first time, it is really slow...

**Comment by Duan-JM** [comment]
@zycv In any case, thanks for this solution~ maybe we can add this suggestion in README to provide a solution for those who encounter this network problem.

**Comment by SunAriesCN** [comment]
> @zycv In any case, thanks for this solution~ maybe we can add this suggestion in README to provide a solution for those who encounter this network problem. 

Yes, we also can open an issue to discuss the slowly building problem. Or, we can write a FQA on wiki to make it be fine to many guys.

**Pull request closed without merging**
